### ISSUE TITLE
changePrefix missed a couple items

### ISSUE THREAD

**Issue by prjemian** [EPICS-synApps/utils#2]
Running changePrefix just now with fresh checkout from master, these items were not changed (along with some documentation that probably does not need to change):

```
start_putrecorder:EPICS_APP=/home/oxygen/MOONEY/epics/synApps/support/xxx
start_putrecorder:MACROS_PY_DIR=${EPICS_APP}/xxxApp/op/python
```

These were identified by running:

```
cd /usr/local/epics/synApps/support/
mkdir ../ioc
tar cf - xxx-R6-0/ | (cd ../ioc && tar xf -)
cd ../ioc/
mv xxx-R6-0/ vm7
cd vm7
changePrefix xxx vm7
git grep xxx
```

**Comment by keenanlang** [comment]
fixed in https://github.com/EPICS-synApps/support/commit/a94b312d8fe90106217968b3afdee34ff770c33d
